version: "3.7"

services:
  heimdall_api:
    container_name: heimdall-api
    restart: always
    build: .
    ports:
      - "8081:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: database
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
